sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kennedy/react-test -f ./client/Dockerfile.dev ./client

#make sure test script exits
script:
  - docker run -e CI=true kennedy/react-test npm test

after_success:
  - docker build -t kennedy/multi-client ./client
  - docker build -t kennedy/multi-nginx ./nginx
  - docker build -t kennedy/multi-server ./server
  - docker build -t kennedy/multi-worker ./worker
    # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
  - docker push kennedy/multi-client
  - docker push kennedy/multi-nginx
  - docker push kennedy/multi-server
  - docker push kennedy/multi-worker