sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 30199278/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 30199278/react-test npm run test — — coverage

after_success:
  - docker build -t 30199278/multi-client ./client
  - docker build -t 30199278/multi-nginx ./nginx
  - docker build -t 30199278/multi-server ./server
  - docker build -t 30199278/multi-worker ./worker
    # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
  - docker push 30199278/multi-client
  - docker push 30199278/multi-nginx
  - docker push 30199278/multi-server
  - docker push 30199278/multi-worker